// <auto-generated />
using System;
using JeffThings.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JeffThings.Migrations
{
    [DbContext(typeof(JeffThingsContext))]
    partial class JeffThingsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JeffThings.Domains.Jogos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Coop")
                        .HasColumnName("COOP");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnName("DATA_LANCAMENTO")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("DESCRICAO")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<decimal>("Preco")
                        .HasColumnName("PRECO")
                        .HasColumnType("smallmoney");

                    b.Property<byte>("TiposJogosId")
                        .HasColumnName("TIPOS_JOGOS_ID");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasName("UQ__JOGOS__E2AB1FF4595C6044");

                    b.HasIndex("TiposJogosId");

                    b.ToTable("JOGOS");
                });

            modelBuilder.Entity("JeffThings.Domains.JogosPlataformas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdJogo")
                        .HasColumnName("ID_JOGO");

                    b.Property<byte>("IdPlataforma")
                        .HasColumnName("ID_PLATAFORMA");

                    b.HasKey("Id");

                    b.HasIndex("IdJogo");

                    b.HasIndex("IdPlataforma");

                    b.ToTable("JOGOS_PLATAFORMAS");
                });

            modelBuilder.Entity("JeffThings.Domains.Plataformas", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("PLATAFORMAS");
                });

            modelBuilder.Entity("JeffThings.Domains.TiposJogos", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("TIPOS_JOGOS");
                });

            modelBuilder.Entity("JeffThings.Domains.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("EMAIL")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("SENHA")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("UQ__USUARIOS__161CF72416821025");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("JeffThings.Domains.Jogos", b =>
                {
                    b.HasOne("JeffThings.Domains.TiposJogos", "TiposJogos")
                        .WithMany("Jogos")
                        .HasForeignKey("TiposJogosId")
                        .HasConstraintName("FK__JOGOS__TIPOS_JOG__59063A47");
                });

            modelBuilder.Entity("JeffThings.Domains.JogosPlataformas", b =>
                {
                    b.HasOne("JeffThings.Domains.Jogos", "IdJogoNavigation")
                        .WithMany("JogosPlataformas")
                        .HasForeignKey("IdJogo")
                        .HasConstraintName("FK__JOGOS_PLA__ID_JO__60A75C0F");

                    b.HasOne("JeffThings.Domains.Plataformas", "IdPlataformaNavigation")
                        .WithMany("JogosPlataformas")
                        .HasForeignKey("IdPlataforma")
                        .HasConstraintName("FK__JOGOS_PLA__ID_PL__619B8048");
                });
#pragma warning restore 612, 618
        }
    }
}
